CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR (15) NOT NULL UNIQUE,
	DATA_NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE,
	STATUS VARCHAR(30) NOT NULL,
	ID_TURMA INT,
	FOREIGN KEY (ID_TURMA)
	REFERENCES TURMA(IDTURMA)

)
GO

CREATE TABLE TURMA(
	IDTURMA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SALA VARCHAR(30) NOT NULL,
	ANO_LETIVO INT NOT NULL,
	TURNO VARCHAR(15) NOT NULL

)
GO

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	NUMERO INT NOT NULL,
	ID_ALUNO INT UNIQUE,
	FOREIGN KEY (ID_ALUNO)
	REFERENCES ALUNO(IDALUNO)

)
GO

CREATE TABLE TELEFONE_ALUNO(
	IDNUMERO INT PRIMARY KEY IDENTITY,
	NUMERO VARCHAR(11),
	TIPO CHAR(3) NOT NULL,
	CHECK(TIPO IN('CEL','COM','RES')),
	ID_ALUNO INT,
	FOREIGN KEY (ID_ALUNO)
	REFERENCES ALUNO(IDALUNO)

)
GO

CREATE TABLE DISCIPLINA(
	IDDISCIPLINA INT PRIMARY KEY IDENTITY,
	CARGA_HORARIA INT NOT NULL,
	NOME VARCHAR(15) NOT NULL

)
GO

CREATE TABLE PROFESSOR(
	IDPROFESSOR INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) UNIQUE,
	SALARIO DECIMAL(10,2) NOT NULL,
	DATA_CONTRATACAO DATE NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE


)
GO

CREATE TABLE ALUNO_DISCIPLINA(
	ID_ALUNO INT,
	ID_DISCIPLINA INT,
	PRIMARY KEY (ID_ALUNO,ID_DISCIPLINA),
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(IDALUNO),
	FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(IDDISCIPLINA)

)
GO

CREATE TABLE PROFESSOR_DISCIPLINA(
	ID_DISCIPLINA INT,
	ID_PROFESSOR INT,
	PRIMARY KEY (ID_DISCIPLINA, ID_PROFESSOR),
	FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(IDDISCIPLINA),
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(IDPROFESSOR)
)
GO

CREATE TABLE TELEFONE_PROFESSOR(
		IDNUMERO INT PRIMARY KEY IDENTITY,
		TIPO CHAR(3) NOT NULL,
		CHECK(TIPO IN('CEL','COM','RES')),
		NUMERO VARCHAR(11) NOT NULL,
		ID_PROFESSOR INT,
		FOREIGN KEY (ID_PROFESSOR)
		REFERENCES PROFESSOR(IDPROFESSOR)
)
GO
